# Generated by Django 5.0.4 on 2024-04-25 21:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagorys', models.CharField(blank=True, max_length=600)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=600)),
            ],
            options={
                'verbose_name': 'Catagory',
                'verbose_name_plural': 'Catagoey',
            },
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_Title', models.CharField(blank=True, max_length=600)),
                ('slug', models.SlugField(unique=True)),
                ('property_short_discription', models.TextField(blank=True)),
                ('property_id', models.UUIDField(default=uuid.uuid4)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('property_size', models.IntegerField()),
                ('property_area', models.IntegerField()),
                ('property_status', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='draft', max_length=100)),
                ('property_lavel', models.CharField(choices=[('Popular', 'Popular'), ('new Property', 'New Property'), ('featured', 'featured Property')], default='draft', max_length=100)),
                ('property_floor', models.IntegerField()),
                ('bedrooms', models.CharField(blank=True, max_length=100)),
                ('bathrooms', models.CharField(blank=True, max_length=100)),
                ('furnished', models.CharField(blank=True, max_length=100)),
                ('main_image', models.ImageField(blank=True, upload_to='products')),
                ('slide_1', models.ImageField(blank=True, upload_to='products')),
                ('slide_2', models.ImageField(blank=True, upload_to='products')),
                ('slide_3', models.ImageField(blank=True, upload_to='products')),
                ('slide_4', models.ImageField(blank=True, upload_to='products')),
                ('slide_5', models.ImageField(blank=True, upload_to='products')),
                ('slide_6', models.ImageField(blank=True, upload_to='products')),
                ('video_link', models.URLField(blank=True, max_length=600)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('property_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signatureapp.catagory')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'Add Property',
            },
        ),
    ]
