# Generated by Django 5.0.4 on 2024-05-15 05:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about')),
                ('hading', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=600)),
                ('video', models.TextField()),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_map', models.CharField(blank=True, max_length=600)),
                ('phone_number', models.CharField(blank=True, max_length=600)),
                ('office_phone', models.CharField(blank=True, max_length=600)),
                ('email', models.CharField(blank=True, max_length=600)),
                ('website', models.CharField(blank=True, max_length=600)),
                ('address', models.CharField(blank=True, max_length=600)),
                ('facebook', models.CharField(blank=True, max_length=600)),
                ('instagram', models.CharField(blank=True, max_length=600)),
                ('linkden', models.CharField(blank=True, max_length=600)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='home info')),
                ('slogon', models.CharField(blank=True, max_length=600)),
                ('title', models.CharField(blank=True, max_length=600)),
                ('video', models.FileField(null=True, upload_to='videos_uploaded')),
            ],
            options={
                'verbose_name': 'home_info',
                'verbose_name_plural': 'Home Information',
            },
        ),
        migrations.CreateModel(
            name='serevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='partners')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('service_name', models.CharField(blank=True, max_length=600)),
                ('short_discriptions', models.TextField()),
                ('Discription', models.TextField()),
            ],
            options={
                'verbose_name': 'serevices',
                'verbose_name_plural': 'Serevices',
            },
        ),
        migrations.CreateModel(
            name='propertys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(blank=True, max_length=600)),
                ('slug', models.SlugField(unique=True)),
                ('property_short_discription', models.TextField(blank=True)),
                ('property_id', models.UUIDField(default=uuid.uuid4)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('property_size', models.IntegerField()),
                ('property_area', models.IntegerField()),
                ('property_status', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='draft', max_length=100)),
                ('facilities', models.CharField(choices=[('air_conditioning', 'Air Conditioning'), ('barbeque', 'Barbeque'), ('dryer', 'Dryer'), ('gym', 'Gym'), ('laundry', 'Laundry'), ('Lawn', 'Lawn'), ('microwave', 'Microwave'), ('outdoor_shower', 'Outdoor Shower'), ('refrigerator', 'Refrigerator'), ('swimming_pool', 'Swimming Pool'), ('tv_cable', 'TV Cable'), ('Washer', 'Washer'), ('WiFi', 'WiFi'), ('window_coverings', 'Window Coverings'), ('CCTV', 'CCTV'), ('Generator', 'Generator'), ('Lift', 'Lift')], default='draft', max_length=100)),
                ('property_floor', models.IntegerField()),
                ('bedrooms', models.CharField(blank=True, max_length=100)),
                ('bathrooms', models.CharField(blank=True, max_length=100)),
                ('furnished', models.CharField(blank=True, max_length=100)),
                ('main_image', models.ImageField(blank=True, upload_to='products')),
                ('slide_1', models.ImageField(blank=True, upload_to='products')),
                ('slide_2', models.ImageField(blank=True, upload_to='products')),
                ('slide_3', models.ImageField(blank=True, upload_to='products')),
                ('slide_4', models.ImageField(blank=True, upload_to='products')),
                ('slide_5', models.ImageField(blank=True, upload_to='products')),
                ('slide_6', models.ImageField(blank=True, upload_to='products')),
                ('video_link', models.URLField(blank=True, max_length=600)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('property_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signatureapp.catagory')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'Add Property',
            },
        ),
        migrations.DeleteModel(
            name='property',
        ),
    ]
