# Generated by Django 5.0.4 on 2024-05-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0002_about_contact_home_serevices_propertys_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name': 'Catagory', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterField(
            model_name='catagory',
            name='icon',
            field=models.ImageField(upload_to='catagory'),
        ),
    ]
