# Generated by Django 5.0.4 on 2024-05-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0003_alter_catagory_options_alter_catagory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertys',
            name='property_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
