# Generated by Django 5.0.4 on 2024-05-15 07:21

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0004_alter_propertys_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertys',
            name='facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('air_conditioning', 'Air Conditioning'), ('barbeque', 'Barbeque'), ('dryer', 'Dryer'), ('gym', 'Gym'), ('laundry', 'Laundry'), ('Lawn', 'Lawn'), ('microwave', 'Microwave'), ('outdoor_shower', 'Outdoor Shower'), ('refrigerator', 'Refrigerator'), ('swimming_pool', 'Swimming Pool'), ('tv_cable', 'TV Cable'), ('Washer', 'Washer'), ('WiFi', 'WiFi'), ('window_coverings', 'Window Coverings'), ('CCTV', 'CCTV'), ('Generator', 'Generator'), ('Lift', 'Lift')], max_length=140),
        ),
    ]
