# Generated by Django 5.0.4 on 2024-05-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0005_alter_propertys_facilities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertys',
            options={'verbose_name': 'propertys', 'verbose_name_plural': 'Propertys '},
        ),
    ]
