# Generated by Django 5.0.4 on 2024-05-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0006_alter_propertys_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertys',
            options={'verbose_name': 'propertys', 'verbose_name_plural': 'Propertys'},
        ),
        migrations.RemoveField(
            model_name='propertys',
            name='facilities',
        ),
    ]
