# Generated by Django 5.0.4 on 2024-05-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0007_alter_propertys_options_remove_propertys_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertys',
            name='property_loacation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
