# Generated by Django 5.0.4 on 2024-05-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0008_propertys_property_loacation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertys',
            old_name='property_loacation',
            new_name='property_location',
        ),
    ]
