# Generated by Django 5.0.4 on 2024-05-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0009_rename_property_loacation_propertys_property_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='egent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_map', models.CharField(blank=True, max_length=600)),
                ('phone_number', models.CharField(blank=True, max_length=600)),
                ('office_phone', models.CharField(blank=True, max_length=600)),
                ('email', models.CharField(blank=True, max_length=600)),
                ('website', models.CharField(blank=True, max_length=600)),
                ('address', models.CharField(blank=True, max_length=600)),
                ('facebook', models.CharField(blank=True, max_length=600)),
                ('instagram', models.CharField(blank=True, max_length=600)),
                ('linkden', models.CharField(blank=True, max_length=600)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
