# Generated by Django 5.0.4 on 2024-05-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0010_egent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egent',
            options={'verbose_name': 'egent', 'verbose_name_plural': 'Egent'},
        ),
        migrations.RenameField(
            model_name='egent',
            old_name='address',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='egent',
            name='google_map',
        ),
        migrations.RemoveField(
            model_name='egent',
            name='website',
        ),
        migrations.AddField(
            model_name='egent',
            name='image',
            field=models.ImageField(blank=True, upload_to='home info'),
        ),
        migrations.AddField(
            model_name='propertys',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signatureapp.egent'),
        ),
    ]
