# Generated by Django 5.0.4 on 2024-05-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0011_alter_egent_options_rename_address_egent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities_name', models.CharField(blank=True, max_length=600)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'facilities',
                'verbose_name_plural': 'Facilities List',
            },
        ),
    ]
