# Generated by Django 5.0.4 on 2024-05-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0012_facilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertys',
            old_name='name',
            new_name='agent',
        ),
    ]
