# Generated by Django 5.0.4 on 2024-05-15 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0013_rename_name_propertys_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertys',
            name='facilitie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signatureapp.facilities'),
        ),
    ]
