# Generated by Django 5.0.4 on 2024-05-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0014_propertys_facilitie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertys',
            name='facilitie',
        ),
        migrations.AddField(
            model_name='propertys',
            name='facilitie',
            field=models.ManyToManyField(to='signatureapp.facilities'),
        ),
    ]
