# Generated by Django 5.0.4 on 2024-05-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0015_remove_propertys_facilitie_propertys_facilitie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serevices',
            name='image',
            field=models.ImageField(blank=True, upload_to='partners'),
        ),
    ]
