# Generated by Django 5.0.4 on 2024-05-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0016_serevices_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='video',
        ),
        migrations.AddField(
            model_name='about',
            name='ceo_description',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='about',
            name='ceo_facebook',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='about',
            name='ceo_image',
            field=models.ImageField(blank=True, upload_to='about'),
        ),
        migrations.AddField(
            model_name='about',
            name='ceo_instagram',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='about',
            name='ceo_linkden',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='about',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='about',
            name='ceo_position',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='about',
            name='mission',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='about',
            name='tytle',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='about',
            name='why_choose_us_header',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='about',
            name='hading',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
