# Generated by Django 5.0.4 on 2024-05-15 21:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0017_remove_about_video_about_ceo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='aboutus',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='ceo_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
