# Generated by Django 5.0.4 on 2024-05-15 21:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0018_about_aboutus_alter_about_ceo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='value',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
