# Generated by Django 5.0.4 on 2024-05-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0019_about_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='aboutus_image',
            field=models.ImageField(blank=True, upload_to='about'),
        ),
        migrations.AddField(
            model_name='about',
            name='mission_image',
            field=models.ImageField(blank=True, upload_to='about'),
        ),
        migrations.AddField(
            model_name='about',
            name='value_image',
            field=models.ImageField(blank=True, upload_to='about'),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_image',
            field=models.ImageField(blank=True, upload_to='about'),
        ),
    ]
