# Generated by Django 5.0.4 on 2024-05-15 21:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0020_about_aboutus_image_about_mission_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
