# Generated by Django 5.0.4 on 2024-05-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0021_about_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='ceo_instagram',
            new_name='ceo_twitter',
        ),
    ]
