# Generated by Django 5.0.4 on 2024-05-20 23:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0022_rename_ceo_instagram_about_ceo_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='ceo_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='serevices',
            name='Discription',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='serevices',
            name='short_discriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
