# Generated by Django 5.0.14 on 2026-06-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0024_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='property_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('property_type', models.CharField(blank=True, max_length=200)),
                ('goal', models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Buy', 'Buy'), ('Invest', 'Invest'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('budget', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('source_page', models.CharField(blank=True, max_length=600)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'property_request',
                'verbose_name_plural': 'Property Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
