# Generated by Django 5.0.14 on 2026-06-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0025_property_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egent',
            options={'verbose_name': 'egent', 'verbose_name_plural': 'Agent'},
        ),
        migrations.AddField(
            model_name='propertys',
            name='price_amount',
            field=models.IntegerField(blank=True, help_text='Numeric price value, parsed from price text', null=True),
        ),
        migrations.AddField(
            model_name='propertys',
            name='price_currency',
            field=models.CharField(blank=True, default='', help_text='ETB, USD, or empty', max_length=8),
        ),
    ]
