# Generated by Django 5.0.14 on 2026-07-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0027_protect_property_lookup_references'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egent',
            options={'ordering': ['-id'], 'verbose_name': 'egent', 'verbose_name_plural': 'Agent'},
        ),
    ]
