# Generated by Django 5.2.15 on 2026-07-19 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0029_clean_property_type_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Signed in'), ('login_failed', 'Failed sign-in')], max_length=20)),
                ('target_model', models.CharField(max_length=150)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=300)),
                ('summary', models.CharField(blank=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activity_log_entry',
                'verbose_name_plural': 'Activity Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
