# Generated by Django 5.2.15 on 2026-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0030_activitylogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=600)),
                ('source', models.CharField(blank=True, help_text='Page or feature that triggered the search', max_length=100)),
                ('location_filter', models.CharField(blank=True, max_length=200)),
                ('property_type', models.CharField(blank=True, max_length=200)),
                ('status_filter', models.CharField(blank=True, max_length=50)),
                ('results_count', models.IntegerField(default=0)),
                ('pathway', models.CharField(blank=True, help_text='How the visitor arrived (landing, direct, organic, etc.)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'search_event',
                'verbose_name_plural': 'Search Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
