# Generated by Django 5.2.16 on 2026-07-22 12:31

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0031_searchevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicespage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=600)),
                ('hero_title', models.CharField(blank=True, max_length=600)),
                ('hero_lead', models.TextField(blank=True)),
                ('intro', ckeditor.fields.RichTextField(blank=True)),
                ('why_choose_title', models.CharField(blank=True, max_length=600)),
                ('process_title', models.CharField(blank=True, max_length=600)),
            ],
            options={
                'verbose_name': 'services page',
                'verbose_name_plural': 'Services Page',
            },
        ),
        migrations.AddField(
            model_name='about',
            name='commitment',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='commitment_promise',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_lead',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='servicespage_process_step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('text', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='signatureapp.servicespage')),
            ],
            options={
                'verbose_name': 'process step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='servicespage_why_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('text', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_items', to='signatureapp.servicespage')),
            ],
            options={
                'verbose_name': 'why choose us item',
                'verbose_name_plural': 'Why Choose Us Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
