# Generated by Django 5.2.16 on 2026-07-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0033_seed_services_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='services'),
        ),
    ]
