# Generated by Django 5.2.16 on 2026-07-22 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0034_servicespage_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCommitmentParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'about commitment paragraph',
                'verbose_name_plural': 'About Commitment Paragraphs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutIntroParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'about intro paragraph',
                'verbose_name_plural': 'About Intro Paragraphs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutValueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('tag', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'about value item',
                'verbose_name_plural': 'About Value Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutWhyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=600)),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'about why choose us item',
                'verbose_name_plural': 'About Why Choose Us Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesPageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('tag', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=600)),
                ('tagline', models.CharField(blank=True, max_length=600)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'services page service',
                'verbose_name_plural': 'Services Page Services',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesPageServiceParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'service paragraph',
                'verbose_name_plural': 'Service Paragraphs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesPageServiceTagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'service tag group',
                'verbose_name_plural': 'Service Tag Groups',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesPageServiceTagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('text', models.CharField(max_length=600)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'service tag item',
                'verbose_name_plural': 'Service Tag Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='about',
            name='hero_eyebrow',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_title',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='about',
            name='mission_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='why_choose_title',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='servicespage_process_step',
            name='key',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicespage_why_item',
            name='key',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='servicespage_process_step',
            constraint=models.UniqueConstraint(fields=('page', 'key'), name='unique_services_process_key'),
        ),
        migrations.AddConstraint(
            model_name='servicespage_why_item',
            constraint=models.UniqueConstraint(fields=('page', 'key'), name='unique_services_why_key'),
        ),
        migrations.AddField(
            model_name='aboutcommitmentparagraph',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_paragraphs', to='signatureapp.about'),
        ),
        migrations.AddField(
            model_name='aboutintroparagraph',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_paragraphs', to='signatureapp.about'),
        ),
        migrations.AddField(
            model_name='aboutvalueitem',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_items', to='signatureapp.about'),
        ),
        migrations.AddField(
            model_name='aboutwhyitem',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_items', to='signatureapp.about'),
        ),
        migrations.AddField(
            model_name='servicespageservice',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='signatureapp.servicespage'),
        ),
        migrations.AddField(
            model_name='servicespageserviceparagraph',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='signatureapp.servicespageservice'),
        ),
        migrations.AddField(
            model_name='servicespageservicetaggroup',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_groups', to='signatureapp.servicespageservice'),
        ),
        migrations.AddField(
            model_name='servicespageservicetagitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='signatureapp.servicespageservicetaggroup'),
        ),
        migrations.AddConstraint(
            model_name='aboutcommitmentparagraph',
            constraint=models.UniqueConstraint(fields=('page', 'key'), name='unique_about_commitment_key'),
        ),
        migrations.AddConstraint(
            model_name='aboutintroparagraph',
            constraint=models.UniqueConstraint(fields=('page', 'key'), name='unique_about_intro_key'),
        ),
        migrations.AddConstraint(
            model_name='aboutvalueitem',
            constraint=models.UniqueConstraint(fields=('page', 'key'), name='unique_about_value_key'),
        ),
        migrations.AddConstraint(
            model_name='aboutwhyitem',
            constraint=models.UniqueConstraint(fields=('page', 'key'), name='unique_about_why_key'),
        ),
        migrations.AddConstraint(
            model_name='servicespageservice',
            constraint=models.UniqueConstraint(fields=('page', 'key'), name='unique_services_page_item_key'),
        ),
        migrations.AddConstraint(
            model_name='servicespageserviceparagraph',
            constraint=models.UniqueConstraint(fields=('service', 'key'), name='unique_service_paragraph_key'),
        ),
        migrations.AddConstraint(
            model_name='servicespageservicetaggroup',
            constraint=models.UniqueConstraint(fields=('service', 'key'), name='unique_service_tag_group_key'),
        ),
        migrations.AddConstraint(
            model_name='servicespageservicetagitem',
            constraint=models.UniqueConstraint(fields=('group', 'key'), name='unique_service_tag_item_key'),
        ),
    ]
