# Generated by Django 5.2.16 on 2026-08-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0037_home_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_form_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('tel', 'Phone'), ('email', 'Email'), ('textarea', 'Paragraph'), ('select', 'Dropdown')], default='text', max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('position', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'request_form_field',
                'verbose_name_plural': 'Request Form Fields',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='property_request',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
