# Generated by Django 5.2.16 on 2026-08-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureapp', '0039_seed_request_form_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_request',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('called', 'Called'), ('talked', 'Talked'), ('followed_up', 'Followed Up'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
